//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace socialNetworkApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string commenter { get; set; }
        public string comment1 { get; set; }
        public int postId { get; set; }
    
        public virtual Post Post { get; set; }
        public List<Links> Links = new List<Links>();
    }
}
